---
- name: Create directory for compose
  file:
    path: "{{app_image_dir}}"
    state: directory
  register: compose_dir
- name: Render docker compose template
  template:
    src: docker-compose.yml.j2
    dest: "{{ app_image_dir }}/docker-compose.yml"
  vars:
    image_full: "{{app_image_name}}:{{app_image_tag}}"
    publish_ports: "5000:5000"
- name: Start  docker
  service:
    name: "docker"
    state: "started"
    enabled: true
- name: Start app service
  community.docker.docker_compose_v2:
    project_src: "{{ app_image_dir }}"
    state: "present"
    remove_orphans: true
- name: Wipe app
  when: app_full_wipe is defined and app_full_wipe
  include_tasks:
    file: "wipe-0.yml"