name: code quality test

on: push

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
     # - name: Run image
      #  uses: abatilo/actions-poetry@v2
      #  with:
       #   poetry-version: '1.7.1'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app_python/requirements.txt
      - name: Test python format using Flake8
        run: flake8
      - name: Test with pytest
        run: pytest .